name: Create Neon Twin (data subset)

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  PROD_DATABASE_URL: ${{ secrets.PROD_DATABASE_URL }}
  DEV_DATABASE_URL: ${{ secrets.DEV_DATABASE_URL }}
  PG_VERSION: '17'

jobs:
  dump-and-restore:
    runs-on: ubuntu-latest

    steps:
      - name: Install PostgreSQL
        run: |
          sudo apt update
          yes '' | sudo /usr/share/postgresql-common/pgdg/apt.postgresql.org.sh
          sudo apt install -y postgresql-${{ env.PG_VERSION }}

      - name: Create temporary table and dump data
        run: |
          psql "${{ env.PROD_DATABASE_URL }}" -c "CREATE TEMP TABLE users_temp AS SELECT * FROM users LIMIT 100;"

          /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/pg_dump "${{ env.PROD_DATABASE_URL }}" -Fc --no-owner --no-acl --data-only \
            --table=users_temp --file="${{ github.workspace }}/prod-dump-file.dump"

          psql "${{ env.PROD_DATABASE_URL }}" -c "DROP TABLE users_temp;"

      - name: Restore data to Neon
        run: |
          /usr/lib/postgresql/${{ env.PG_VERSION }}/bin/pg_restore -d "${{ env.DEV_DATABASE_URL }}" --clean --no-owner --no-acl --if-exists "${{ github.workspace }}/prod-dump-file.dump"
